language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.05 PACKAGE=landmarks TESTS=true
  - OCAML_VERSION=4.06 PACKAGE=landmarks TESTS=true
  - OCAML_VERSION=4.07 PACKAGE=landmarks TESTS=true
  - OCAML_VERSION=4.08 PACKAGE=landmarks TESTS=true
  - OCAML_VERSION=4.09 PACKAGE=landmarks TESTS=true
  - OCAML_VERSION=4.10 PACKAGE=landmarks TESTS=true
os:
  - linux
  - osx
